export const WORKSHOP_ROUTES = [
  {
    file: "0-full-content.html",
    entry: "0-full-content",
    title: "完整工作坊內容",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: false,
  },
  {
    file: "1-introduction.html",
    entry: "1-introduction",
    title: "這個工作坊是什麼，以及不是什麼",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "2-what-is-llm.html",
    entry: "2-what-is-llm",
    title: "什麼是大型語言模型？",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "3-1-chatbot-interface.html",
    entry: "3-1-chatbot-interface",
    title: "聊天機器人介面",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "3-2-providers-models.html",
    entry: "3-2-providers-models",
    title: "供應商與模型",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "3-3-context-window.html",
    entry: "3-3-context-window",
    title: "上下文視窗",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "3-4-document-upload.html",
    entry: "3-4-document-upload",
    title: "文件上傳",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "3-5-multi-document.html",
    entry: "3-5-multi-document",
    title: "多份文件",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "3-6-image-demo.html",
    entry: "3-6-image-demo",
    title: "圖片理解",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "3-7-hidden-costs.html",
    entry: "3-7-hidden-costs",
    title: "隱藏成本",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "3-8-practice.html",
    entry: "3-8-practice",
    title: "聊天機器人重點整理",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-1-personas.html",
    entry: "4-1-personas",
    title: "角色設定",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-2-structured-io.html",
    entry: "4-2-structured-io",
    title: "結構化輸入與輸出",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-3-chain-of-thought.html",
    entry: "4-3-chain-of-thought",
    title: "深度思考（Reasoning）",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-4-grounding.html",
    entry: "4-4-grounding",
    title: "提供參考資料",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-5-nlp-tasks.html",
    entry: "4-5-nlp-tasks",
    title: "自然語言處理任務",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-6-few-shot.html",
    entry: "4-6-few-shot",
    title: "提供範例",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-7-prompt-chaining.html",
    entry: "4-7-prompt-chaining",
    title: "拆解任務",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-8-self-correction.html",
    entry: "4-8-self-correction",
    title: "自我修正",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-9-prompt-injection.html",
    entry: "4-9-prompt-injection",
    title: "提示注入：紅隊測試與防線觀察",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-10-takeaways.html",
    entry: "4-10-takeaways",
    title: "提示技巧重點整理",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "4-overview.html",
    entry: "4-overview",
    title: "提示技巧總覽",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "5-1-tool-invocation.html",
    entry: "5-1-tool-invocation",
    title: "5.1 工具呼叫",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "5-2-calculator-tool.html",
    entry: "5-2-calculator-tool",
    title: "5.2 計算機工具",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "5-3-datetime-tool.html",
    entry: "5-3-datetime-tool",
    title: "5.3 日期／時間工具",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "5-4-websearch-tool.html",
    entry: "5-4-websearch-tool",
    title: "5.4 網路搜尋工具",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "5-5-artifacts-tool.html",
    entry: "5-5-artifacts-tool",
    title: "5.5 產物工具（Artifacts）",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "5-6-mcp.html",
    entry: "5-6-mcp",
    title: "5.6 模型上下文協定（MCP）",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "5-7-key-takeaways.html",
    entry: "5-7-key-takeaways",
    title: "5.7 AI 代理人重點整理",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "5-overview.html",
    entry: "5-overview",
    title: "5. AI 代理人：讓大型語言模型使用工具",
    htmlClass: "h-full",
    bodyClass: "h-full overflow-hidden",
    includeThemeBootstrap: true,
    smoke: true,
  },
  {
    file: "6-1-models.html",
    entry: "6-1-models",
    title: "6.1 模型：要跑什麼、去哪裡找",
    htmlClass: "bg-background",
    bodyClass: "",
    includeThemeBootstrap: false,
    smoke: true,
  },
  {
    file: "6-2-software-stack.html",
    entry: "6-2-software-stack",
    title: "6.2 了解軟體堆疊",
    htmlClass: "bg-background",
    bodyClass: "",
    includeThemeBootstrap: false,
    smoke: true,
  },
  {
    file: "6-3-hardware.html",
    entry: "6-3-hardware",
    title: "6.3 你實際需要的硬體",
    htmlClass: "bg-background",
    bodyClass: "",
    includeThemeBootstrap: false,
    smoke: true,
  },
  {
    file: "6-4-demos.html",
    entry: "6-4-demos",
    title: "6.4 實作示範",
    htmlClass: "bg-background",
    bodyClass: "",
    includeThemeBootstrap: false,
    smoke: true,
  },
  {
    file: "6-overview.html",
    entry: "6-overview",
    title: "6. 自行託管 LLM",
    htmlClass: "bg-background",
    bodyClass: "",
    includeThemeBootstrap: false,
    smoke: true,
  },
  {
    file: "7-where-to-go.html",
    entry: "7-where-to-go",
    title: "7. 接下來可以往哪裡走",
    htmlClass: "bg-background",
    bodyClass: "",
    includeThemeBootstrap: false,
    smoke: true,
  },
  {
    file: "index.html",
    entry: "index",
    title: "生成式人工智慧工作坊",
    htmlClass: "bg-background",
    bodyClass: "",
    includeThemeBootstrap: true,
    smoke: true,
  },
];

export function listWorkshopRoutes(options = {}) {
  const { includeFullContent = true, smokeOnly = false } = options;
  return WORKSHOP_ROUTES.filter(
    (route) => includeFullContent || route.file !== "0-full-content.html",
  )
    .filter((route) => !smokeOnly || route.smoke !== false)
    .map((route) => ({ ...route }));
}
